# Redis with official RedisBloom, JSON, Search modules, ... etc
FROM redis/redis-stack-server:latest

# (Optional) place a redis.conf if you want to tweak settings:
# COPY redis.conf /usr/local/etc/redis/redis.conf
# CMD ["redis-server", "/usr/local/etc/redis/redis.conf"]